### ISSUE TITLE
Error admob fail_to_load

### ISSUE THREAD

**Issue by grevius5** [yalcin-ata/godot-android-module-firebase#1]
I think it will be great if we could get some information about the error we are incurring when an ad is not loaded.
`public void onAdFailedToLoad(int errorCode) {
                bannerLoaded = false;
                Utils.callScriptFunc("AdMob", "Banner", "on_ad_failed_to_load");
}`

Here we can print the error type to the logcat or better send it to Godot.

**Comment by yalcin-ata** [comment]
Yes, you are right. I added the errorCode value to the callbacks (and updated the [API ](https://github.com/yalcin-ata/godot-android-module-firebase/blob/master/INSTRUCTIONS.md#callbacks-fired-when-admob-is-initialized)description).
