### ISSUE TITLE
Set test banner without change android project settings

### ISSUE THREAD

**Issue by grevius5** [yalcin-ata/godot-android-module-firebase#2]
I think it would be great if we can set the test mode for ads in the Firebase init function and not by changing always the android project file. I test with a physical device and i have to switch the "test" bool always for production and test.
A valid alternative would be to set a test device [with this](https://developers.google.com/admob/android/test-ads#add_your_test_device).
Let me know what you think :)

**Comment by yalcin-ata** [comment]
It could be done, but I don't think it is neccessary because in my workflow the test option is always on. Only when I am about to release the APK I turn it off.
