### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by mthnzbk** [yalcin-ata/godot-android-module-firebase#4]
When I log in with google, the callback output looks like this: Firebase Authentication Google other

```
print(Firebase.firebase.authentication_google_is_connected())
print(Firebase.firebase.authentication_google_get_user())
print(Firebase.firebase.authentication_get_id_token())
```

Output with these codes: false, null, null

**Comment by yalcin-ata** [comment]
If you get the callback "Firebase Authentication Google other" it is most likely the log-in was not successful. Have you enabled the Google authentification sign-in method in your project's Firebase console? (See README> Authentication > 1. Go to project's Firebase Console > Authentication > Sign-in method > Google: enable.)

As for ```print(Firebase.firebase.authentication_get_id_token())```: it's return type is void. You will get the data in the callback (see the API documentation in INSTRUCTIONS).

**Comment by mthnzbk** [comment]
Yes, google is active. The callback output is always the same when I log in.

**Comment by mthnzbk** [comment]
Game: https://paste.ubuntu.com/p/DmfWCK64b6/
FirebaseSingleton: https://paste.ubuntu.com/p/TzXgqxPJqk/

**Comment by himaghnam** [comment]
Any success, I am having the same problem
