### ISSUE TITLE
I'm not able to build on android

### ISSUE THREAD

**Issue by Lucas-B-C-Oliveira** [yalcin-ata/godot-android-module-firebase#6]
![image](https://user-images.githubusercontent.com/33939027/81493550-7e8aa380-9277-11ea-824b-8cfc4ce18a6d.png)

I followed the tutorial correctly, only in part 12: 

 ([PROJECT]/android/godot-android-modules-firebase/AndroidManifest.conf), 

I kept it as it was, because I didn't know what my preference was.

When I try to build on android, I get this error.

NOTE: I am using godot version 3.2.1, is there a problem?

Sorry for the inconvenience, thank you for your attention

**Comment by lucascoliveira189** [comment]
![image](https://user-images.githubusercontent.com/33939027/81244800-afee3f80-8fe9-11ea-8b2a-abe4725513b7.png)

**Comment by yalcin-ata** [comment]
Do you run it on an Android device or on your computer?

**Comment by lucascoliveira189** [comment]
In computer

**Comment by lucascoliveira189** [comment]
![image](https://user-images.githubusercontent.com/33939027/81461302-3d17cc80-9181-11ea-9a47-4422f025425b.png)


I'm testing in Android device, but i have this error :((

**Comment by Lucas-B-C-Oliveira** [comment]
I found a solution, it's solved, thanks

**Comment by Lucas-B-C-Oliveira** [comment]
I was changing the APPLICATION_ID
```
ERROR:
<meta-data
    android:name="com.google.android.gms.ads.br.com.mypackeged"
    android:value="ca-app-pub-8792695908573542~8144327831"/> 

RIGHT:  
<meta-data
    android:name="com.google.android.gms.ads.APPLICATION_ID"
    android:value="ca-app-pub-8792695908573542~8144327831"/>``
