### ISSUE TITLE
firestore functions are not working :(

### ISSUE THREAD

**Issue by Lucas-B-C-Oliveira** [yalcin-ata/godot-android-module-firebase#7]
**Hi friend**, I have a **problem changing or getting** data from the **Database**.

The functions:

`firebase.firestore_add_document ("collectionName", Dictionary) -> void`

`firebase.firestore_set_document_data ("collectionName", "documentName", Dictionary) -> void`

**return data == false  `¯\_(ツ)_/¯`** 

however, the function:

`firebase.firestore_load_document ("collectionName") -> void`

it simply doesn't return anything, when I put it in a variable, it **returns NULL**

**What am I doing wrong?**

**_Please help me, I really need to solve this problem for my final project in college, thank you !!!_**

**_My project is here_**: https://github.com/lucascoliveira189/PLComUno

**My Code**
![image](https://user-images.githubusercontent.com/33939027/81508972-ca703380-92dd-11ea-8419-6def59cf4b4f.png)

**My Database**
![image](https://user-images.githubusercontent.com/33939027/81508983-d956e600-92dd-11ea-88f8-4459b92a56dc.png)

**Result in Debug**
![image](https://user-images.githubusercontent.com/33939027/81508996-ec69b600-92dd-11ea-85d2-ca7754257612.png)

**Comment by yalcin-ata** [comment]
I checked again by creating a minimal test project, and everything works as intended. My first assumption is that you did not set up the access rights to the Firebase Firestore database.
