### ISSUE TITLE
RewardedVideo status tag problem

### ISSUE THREAD

**Issue by kristijandraca** [yalcin-ata/godot-android-module-firebase#9]
You have a different status message for "AdMob", "RewardedVideo"

Inside Ads.java 
lines 322 and 327
Utils.callScriptFunc("AdMob", "RewardedVideo", buildStatus(unitid, "on_rewarded_ad_loaded"));
 Utils.callScriptFunc("AdMob", "RewardedVideo", buildStatus(unitid, "on_rewarded_ad_failed_to_load:" + errorCode));

lines 283
Utils.callScriptFunc("AdMob", "RewardedVideo", buildStatus(unit_id, rewardedVideoAds.get(unit_id).isLoaded() ? "loaded" : "not_loaded"));

So  loaded and  on_rewarded_ad_loaded and  on_rewarded_ad_failed_to_load and not_loaded

**Comment by yalcin-ata** [comment]
The latter is for a check if a rewarded video is loaded (and ready), the former is a callback from requesting rewarded video.
